import { Cart } from './shared/models/Cart';

export const fitness_cart: Cart[] = [
  {
    id: '1',
    name: 'Pulse',
    price: 80,
    threeMonthsPrice: 220,
    pricePerYear: 800,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    // tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Titanium',
    price: 60,
    threeMonthsPrice: 165,
    pricePerYear: 600,
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    // tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Flais',
    price: 50,
    threeMonthsPrice: 135,
    pricePerYear: 400,
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    // tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Next Level',
    price: 75,
    threeMonthsPrice: 205,
    pricePerYear: 750,
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    // tags: ['FastFood', 'Fry'],
  },
];
